Rule induction
PWR-Informatyka-biomedyczna/DoggOSFuzzy pull request #72
Opened 2021-07-27 15:49 UTC by Adam-Chlopowiec

2021-07-29 19:32 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/fuzzy_decision_table_generator.py
> +        self.__dataset['Decision'] = y
Imo, these operations shouldn't be performed in constructor - to fuzzify different dataset one would need to create a new object. More convenient would be to pass this data to fuzzify method. Your approach could be reasonable if the fuzzified data would be also held in self.

2021-07-29 19:32 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/fuzzy_decision_table_generator.py
> +                if column is 'Decision':
Inconsistency in comparison with line 93

2021-07-29 19:32 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/fuzzy_decision_table_generator.py
> +                                                                        self.__fuzzy_sets[feature.name][key]))
Probably should be in different, private method

2021-07-29 19:32 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/fuzzy_decision_table_generator.py
> +        :param feature: a name of a feature for which to determine a name of the highest membership set
Fix this sentence pls - "for which to" part is weird

2021-07-29 19:32 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/fuzzy_decision_table_generator.py
> +        :return: a name of a fuzzy set with the highest member value for a given feature
Not membership value?

2021-07-29 19:32 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +    def __init__(self, decision_table: pd.DataFrame, feature_labels: List[str]):
No docstring

2021-08-03 22:12 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +        labels of feature to consider for calculating identity
features*

2021-08-03 22:12 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +        subset of dataset that is consistent
size of subset*

2021-08-03 22:12 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +        :return: decision table without inconsistencies and count of changed decisions
either class docstring about clean_decisions is wrong or this

2021-08-03 22:12 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +        samples = self.__dataset.copy()
same as line 51?

2021-08-03 22:12 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +    def _find_lower_approx(self, conflicts: pd.DataFrame) -> NoReturn:
Could be more intuitive if _find_lower_approx returned self.__clean_decisions aswell, so the flow of class if easier to follow from the public method itself. Not sure about that, cause self._solve_conflicts would also have to have an additional argument - clean_decisions

2021-08-04 15:50 UTC, Adam-Chlopowiec commented on doggos/induction/rule_induction_WIP/inconsistencies_remover.py
> +    def _find_lower_approx(self, conflicts: pd.DataFrame) -> NoReturn:
Since it is protected method I don't think this conception is superior to already existing one.

2021-08-04 18:50 UTC, Adrian-Chlopowiec requested changes

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/inconsistencies_remover.py
> +        dataset containing possible inconsistencies
fuzzified dataset*

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/inconsistencies_remover.py
> +        labels of feature to consider for calculating samples identity
features*

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/inconsistencies_remover.py
> +            self.__clean_decisions = self.__clean_decisions.drop(index=index, axis=0)
check whether its possible to do .drop(index=indices_to_remove)

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/information_system.py
> +    Class for inducing rule antecedents from a dataset:
rules*

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_builder.py
> +        clauses from feature names and corresponding datasets
features names*

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_builder.py
> +        algebra = GodelAlgebra()
should be argument to method

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/rule_builder.py
> +            decision_rules[decision], string_antecedents[decision] = self.__build_rules(differences, idx_rows)
Merge with previous for loop

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/information_system.py
> +        data representing objects
objects -> samples

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/information_system.py
> +        target values for corresponding objects
objects -> samples

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/induction/information_system.py
> +        :param y: target values for corresponding objects
objects -> samples

2021-08-04 18:50 UTC, Adrian-Chlopowiec commented on doggos/knowledge/term.py
> +        self.name = name
Change default name to LinguisticVariable::name + " _" + clause.gradation_adj

2021-08-05 11:11 UTC, Adrian-Chlopowiec approved these changes

2021-08-05 11:11 UTC, merged